# Cloudflare Pages configuration

[build]
  command = "chmod +x ./cloudflare-build.sh && ./cloudflare-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.9.0"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 